In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.externals import joblib


/home/siddanath/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [4]:
#Creating Dataset and including the first row by setting no header as input
 #= pd.read_csv('iris.data.csv', header = None)
dataset = pd.read_csv('/home/siddanath/important/My_projects/ML/MulticlassClassification/TwitterDataAnalysis-master/DataSet.csv')
#Renaming the columns
dataset=dataset.drop(['Unnamed: 0'],axis=1)
#dataset.columns = ['retweet_count', 'favorite_count','petal length in cm','petal width in cm','species']
#print('Shape of the dataset: ' + str(dataset.shape))
print(dataset.head())


   retweet_count  favorite_count  followers_count  predict_class_label  \
0            254             814          43.0000                    4   
1              0               2           0.1360                    2   
2              1               0           0.0364                    4   
3             14               0           1.4300                    4   
4            685               0           0.4350                    1   

   Date_class  
0           0  
1           4  
2           3  
3           1  
4           2  


In [5]:
dataset

retweet_count  favorite_count  followers_count  predict_class_label  \
0                254             814          43.0000                    4   
1                  0               2           0.1360                    2   
2                  1               0           0.0364                    4   
3                 14               0           1.4300                    4   
4                685               0           0.4350                    1   
5                  7               0           0.4350                    1   
6                287            1537           6.8200                    2   
7                  1               4           1.4300                    4   
8               1094               0           0.4350                    1   
9                 18               0           0.4350                    3   
10                50               0           6.8200                    1   
11                18               0           0.4350                    3   
12                10              44           1.4300                    4   
13              2576               0           6.8200                    4   
14                13               0           0.0364                    4   
15              4302               0           0.4350                    1   
16               113               0          43.0000                    2   
17                30             139           6.8200                    4   
18                16               0           1.4300                    1   
19              1538            2184          43.0000                    2   
20               211             602          43.0000                    2   
21                 0              10           0.0364                    4   
22                53             246           1.4300                    3   
23                 0               2           0.0364                    4   
24                10              65           0.1360                    2   
25                 7              16           0.1360                    2   
26               125             425           0.4350                    4   
27                 3              37           1.4300                    4   
28                 1               1           0.1360                    4   
29              2733            4972          43.0000                    2   
...              ...             ...              ...                  ...   
38704              0               3           1.4300                    2   
38705              8             154           6.8200                    4   
38706              0               1           1.4300                    4   
38707              6              19           0.1360                    3   
38708            699            3942           6.8200                    4   
38709              0               5           1.4300                    2   
38710             25             211           6.8200                    4   
38711           7582               0           6.8200                    4   
38712           2456           13094          43.0000                    2   
38713           3700               0           0.4350                    4   
38714            125             319           1.4300                    4   
38715            207               0           1.4300                    2   
38716              0               0           0.1360                    2   
38717            328               0           0.1360                    4   
38718              0               2           1.4300                    2   
38719            870            2406           6.8200                    2   
38720           3894           13811           6.8200                    3   
38721           2236            8690          43.0000                    2   
38722           1031               0           0.4350                    1   
38723            125         

In [39]:
#Creating the dependent variable class
factor = pd.factorize(dataset['Date_class'])
dataset.Date_class = factor[0]
definitions = factor[1]
print(dataset.Date_class.head())
print(definitions)

0    0
1    1
2    2
3    3
4    4
Name: Date_class, dtype: int64
Int64Index([0, 1, 2, 3, 4], dtype='int64')


In [40]:
definitions

Int64Index([0, 1, 2, 3, 4], dtype='int64')

In [41]:
#Splitting the data into independent and dependent variables
X = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4].values
print('The independent features set: ')
print(X[:5,:])
print('The dependent variable: ')
print(y[:5])

The independent features set: 
[[2.54e+02 8.14e+02 4.30e+01 4.00e+00]
 [0.00e+00 2.00e+00 1.36e-01 2.00e+00]
 [1.00e+00 0.00e+00 3.64e-02 4.00e+00]
 [1.40e+01 0.00e+00 1.43e+00 4.00e+00]
 [6.85e+02 0.00e+00 4.35e-01 1.00e+00]]
The dependent variable: 
[0 1 2 3 4]


In [42]:
y

array([0, 1, 2, ..., 0, 4, 4])

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 21)

In [44]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [77]:
classifier = RandomForestClassifier(n_estimators =200, criterion = 'entropy', random_state = 42,max_depth=80,max_features='sqrt')
classifier.fit(X_train, y_train)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=80, max_features='sqrt', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=1,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [78]:
y_pred = classifier.predict(X_test)
#Reverse factorize (converting y_pred from 0s,1s and 2s to Iris-setosa, Iris-versicolor and Iris-virginica
reversefactor = dict(zip(range(6),definitions))
y_test = np.vectorize(reversefactor.get)(y_test)
y_pred = np.vectorize(reversefactor.get)(y_pred)
 #Making the Confusion Matrix
print(pd.crosstab(y_test, y_pred, rownames=['Actual class'], colnames=['Predicted class']))


Predicted class     0    1     2    3    4
Actual class                              
0                1540  152   550  119  131
1                 170  793   412   19   21
2                 349  210  2309  150  174
3                 144    8   186  696  129
4                 158   21   237  139  867


In [79]:
print(list(zip(dataset.columns[0:4], classifier.feature_importances_)))
joblib.dump(classifier, 'randomforestmodel.pkl') 

[('retweet_count', 0.495136096180049), ('favorite_count', 0.2874685387288849), ('followers_count', 0.16048813401946685), ('predict_class_label', 0.05690723107159913)]


['randomforestmodel.pkl']

In [80]:
from sklearn.metrics import accuracy_score


In [81]:
accuracy_score(y_test, y_pred)

0.6407476249483685

In [186]:
print(classifier.predict(X_test))

[3 0 0 ... 1 0 0]


In [187]:
print(X_test[3])

[-0.04349897  0.15709785 -0.11251826  1.05185339]


In [188]:
lol_=[[254 814 43 4]
      [0 2 0.1360 2 ]
      [1 0 0.0364 4]]

SyntaxError: invalid syntax (<ipython-input-188-2dbdda235e27>, line 1)

In [39]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import svm
model = AdaBoostClassifier()
model.fit(X_train, y_train)
classi = LogisticRegression(random_state=77, solver='lbfgs', multi_class='multinomial').fit(X_train, y_train)
...                         

Ellipsis

In [40]:
model.score(X_test,y_test)

0.32930607187112765

In [41]:
classi.score(X_test,y_test)

0.3347790169351508

In [43]:
clf = svm.SVC(gamma=0.001,decision_function_shape='ovo').fit(X_train, y_train)


In [44]:
clf.score(X_test,y_test)

0.33560512185047503

In [15]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(random_state = 42)

from pprint import pprint

# Look at parameters used by our current forest
print('Parameters currently in use:\n')
pprint(rf.get_params())

Parameters currently in use:

{'bootstrap': True,
 'criterion': 'mse',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 10,
 'n_jobs': 1,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}


In [16]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestClassifier(random_state = 42)

from pprint import pprint

# Look at parameters used by our current forest
print('Parameters currently in use:\n')
pprint(rf.get_params())

Parameters currently in use:

{'bootstrap': True,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 10,
 'n_jobs': 1,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}


In [50]:
from sklearn.model_selection import RandomizedSearchCV

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 20, stop = 500, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
criterion = ['gini','entropy']
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'criterion': criterion,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

pprint(random_grid)

{'bootstrap': [True, False],
 'criterion': ['gini', 'entropy'],
 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None],
 'max_features': ['auto', 'sqrt'],
 'min_samples_leaf': [1, 2, 4],
 'min_samples_split': [2, 5, 10],
 'n_estimators': [20, 73, 126, 180, 233, 286, 340, 393, 446, 500]}


In [51]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestClassifier()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)

# Fit the random search model
rf_random.fit(X_train,y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] n_estimators=286, min_samples_split=10, min_samples_leaf=2, max_features=sqrt, max_depth=20, criterion=entropy, bootstrap=False 
[CV] n_estimators=286, min_samples_split=10, min_samples_leaf=2, max_features=sqrt, max_depth=20, criterion=entropy, bootstrap=False 
[CV] n_estimators=286, min_samples_split=10, min_samples_leaf=2, max_features=sqrt, max_depth=20, criterion=entropy, bootstrap=False 
[CV] n_estimators=20, min_samples_split=5, min_samples_leaf=4, max_features=auto, max_depth=20, criterion=gini, bootstrap=False 
[CV] n_estimators=20, min_samples_split=5, min_samples_leaf=4, max_features=auto, max_depth=20, criterion=gini, bootstrap=False 
[CV] n_estimators=20, min_samples_split=5, min_samples_leaf=4, max_features=auto, max_depth=20, criterion=gini, bootstrap=False 
[CV] n_estimators=126, min_samples_split=5, min_samples_leaf=2, max_features=auto, max_depth=20, criterion=gini, bootstrap=True 
[CV] n_estimators=1

[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:   58.3s


[CV]  n_estimators=393, min_samples_split=2, min_samples_leaf=2, max_features=auto, max_depth=90, criterion=entropy, bootstrap=False, total=  35.3s
[CV] n_estimators=340, min_samples_split=5, min_samples_leaf=1, max_features=auto, max_depth=90, criterion=entropy, bootstrap=True 
[CV]  n_estimators=393, min_samples_split=2, min_samples_leaf=2, max_features=auto, max_depth=90, criterion=entropy, bootstrap=False, total=  36.1s
[CV] n_estimators=340, min_samples_split=5, min_samples_leaf=1, max_features=auto, max_depth=90, criterion=entropy, bootstrap=True 
[CV]  n_estimators=500, min_samples_split=5, min_samples_leaf=2, max_features=auto, max_depth=80, criterion=entropy, bootstrap=True, total=  31.8s
[CV] n_estimators=340, min_samples_split=5, min_samples_leaf=1, max_features=auto, max_depth=90, criterion=entropy, bootstrap=True 
[CV]  n_estimators=500, min_samples_split=5, min_samples_leaf=2, max_features=auto, max_depth=80, criterion=entropy, bootstrap=True, total=  33.2s
[CV] n_estimat

[CV] n_estimators=286, min_samples_split=10, min_samples_leaf=4, max_features=sqrt, max_depth=60, criterion=gini, bootstrap=True 
[CV]  n_estimators=340, min_samples_split=5, min_samples_leaf=2, max_features=auto, max_depth=10, criterion=entropy, bootstrap=False, total=  18.6s
[CV] n_estimators=126, min_samples_split=5, min_samples_leaf=1, max_features=sqrt, max_depth=30, criterion=entropy, bootstrap=False 
[CV]  n_estimators=233, min_samples_split=5, min_samples_leaf=2, max_features=sqrt, max_depth=100, criterion=entropy, bootstrap=False, total=  21.3s
[CV] n_estimators=126, min_samples_split=5, min_samples_leaf=1, max_features=sqrt, max_depth=30, criterion=entropy, bootstrap=False 
[CV]  n_estimators=233, min_samples_split=5, min_samples_leaf=2, max_features=sqrt, max_depth=100, criterion=entropy, bootstrap=False, total=  22.5s
[CV] n_estimators=126, min_samples_split=5, min_samples_leaf=1, max_features=sqrt, max_depth=30, criterion=entropy, bootstrap=False 
[CV]  n_estimators=340, m

[CV]  n_estimators=180, min_samples_split=5, min_samples_leaf=1, max_features=sqrt, max_depth=90, criterion=gini, bootstrap=True, total=   6.4s
[CV] n_estimators=446, min_samples_split=2, min_samples_leaf=1, max_features=auto, max_depth=50, criterion=entropy, bootstrap=True 
[CV]  n_estimators=180, min_samples_split=5, min_samples_leaf=1, max_features=sqrt, max_depth=90, criterion=gini, bootstrap=True, total=   6.4s
[CV] n_estimators=393, min_samples_split=2, min_samples_leaf=4, max_features=auto, max_depth=70, criterion=gini, bootstrap=True 
[CV]  n_estimators=180, min_samples_split=5, min_samples_leaf=1, max_features=sqrt, max_depth=90, criterion=gini, bootstrap=True, total=   6.3s
[CV]  n_estimators=500, min_samples_split=5, min_samples_leaf=4, max_features=sqrt, max_depth=60, criterion=entropy, bootstrap=False, total=  40.4s
[CV] n_estimators=393, min_samples_split=2, min_samples_leaf=4, max_features=auto, max_depth=70, criterion=gini, bootstrap=True 
[CV] n_estimators=393, min_sam

[CV] n_estimators=286, min_samples_split=10, min_samples_leaf=4, max_features=auto, max_depth=60, criterion=entropy, bootstrap=True 
[CV]  n_estimators=286, min_samples_split=2, min_samples_leaf=4, max_features=sqrt, max_depth=10, criterion=gini, bootstrap=False, total=   8.0s
[CV] n_estimators=286, min_samples_split=10, min_samples_leaf=4, max_features=auto, max_depth=60, criterion=entropy, bootstrap=True 
[CV]  n_estimators=286, min_samples_split=2, min_samples_leaf=4, max_features=sqrt, max_depth=10, criterion=gini, bootstrap=False, total=   8.0s
[CV] n_estimators=180, min_samples_split=5, min_samples_leaf=4, max_features=sqrt, max_depth=None, criterion=entropy, bootstrap=True 
[CV]  n_estimators=340, min_samples_split=10, min_samples_leaf=4, max_features=auto, max_depth=50, criterion=entropy, bootstrap=True, total=  18.7s
[CV] n_estimators=180, min_samples_split=5, min_samples_leaf=4, max_features=sqrt, max_depth=None, criterion=entropy, bootstrap=True 
[CV]  n_estimators=180, min_

[CV]  n_estimators=126, min_samples_split=2, min_samples_leaf=1, max_features=auto, max_depth=90, criterion=entropy, bootstrap=False, total=  13.5s
[CV] n_estimators=286, min_samples_split=2, min_samples_leaf=4, max_features=sqrt, max_depth=40, criterion=entropy, bootstrap=True 
[CV]  n_estimators=126, min_samples_split=2, min_samples_leaf=1, max_features=auto, max_depth=90, criterion=entropy, bootstrap=False, total=  14.6s
[CV] n_estimators=286, min_samples_split=2, min_samples_leaf=4, max_features=sqrt, max_depth=40, criterion=entropy, bootstrap=True 
[CV]  n_estimators=126, min_samples_split=2, min_samples_leaf=1, max_features=auto, max_depth=90, criterion=entropy, bootstrap=False, total=  13.1s
[CV] n_estimators=20, min_samples_split=5, min_samples_leaf=1, max_features=auto, max_depth=30, criterion=gini, bootstrap=False 


[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:  5.7min


[CV]  n_estimators=393, min_samples_split=2, min_samples_leaf=4, max_features=auto, max_depth=80, criterion=gini, bootstrap=False, total=  18.5s
[CV] n_estimators=20, min_samples_split=5, min_samples_leaf=1, max_features=auto, max_depth=30, criterion=gini, bootstrap=False 
[CV]  n_estimators=20, min_samples_split=5, min_samples_leaf=1, max_features=auto, max_depth=30, criterion=gini, bootstrap=False, total=   1.0s
[CV] n_estimators=20, min_samples_split=5, min_samples_leaf=1, max_features=auto, max_depth=30, criterion=gini, bootstrap=False 
[CV]  n_estimators=20, min_samples_split=5, min_samples_leaf=1, max_features=auto, max_depth=30, criterion=gini, bootstrap=False, total=   1.0s
[CV] n_estimators=233, min_samples_split=2, min_samples_leaf=4, max_features=auto, max_depth=20, criterion=entropy, bootstrap=True 
[CV]  n_estimators=20, min_samples_split=5, min_samples_leaf=1, max_features=auto, max_depth=30, criterion=gini, bootstrap=False, total=   0.9s
[CV] n_estimators=233, min_sample

[CV] n_estimators=126, min_samples_split=5, min_samples_leaf=1, max_features=auto, max_depth=40, criterion=gini, bootstrap=False 
[CV]  n_estimators=233, min_samples_split=10, min_samples_leaf=2, max_features=sqrt, max_depth=70, criterion=entropy, bootstrap=False, total=  19.4s
[CV] n_estimators=126, min_samples_split=5, min_samples_leaf=1, max_features=auto, max_depth=40, criterion=gini, bootstrap=False 
[CV]  n_estimators=126, min_samples_split=5, min_samples_leaf=1, max_features=auto, max_depth=40, criterion=gini, bootstrap=False, total=   6.2s
[CV] n_estimators=126, min_samples_split=5, min_samples_leaf=1, max_features=auto, max_depth=40, criterion=gini, bootstrap=False 
[CV]  n_estimators=126, min_samples_split=5, min_samples_leaf=1, max_features=auto, max_depth=40, criterion=gini, bootstrap=False, total=   6.1s
[CV] n_estimators=446, min_samples_split=2, min_samples_leaf=4, max_features=sqrt, max_depth=100, criterion=entropy, bootstrap=False 
[CV]  n_estimators=126, min_samples_s

[CV]  n_estimators=286, min_samples_split=2, min_samples_leaf=2, max_features=sqrt, max_depth=70, criterion=entropy, bootstrap=True, total=  19.1s
[CV] n_estimators=20, min_samples_split=5, min_samples_leaf=1, max_features=sqrt, max_depth=10, criterion=entropy, bootstrap=True 
[CV]  n_estimators=286, min_samples_split=2, min_samples_leaf=2, max_features=sqrt, max_depth=70, criterion=entropy, bootstrap=True, total=  18.7s
[CV] n_estimators=20, min_samples_split=5, min_samples_leaf=1, max_features=sqrt, max_depth=10, criterion=entropy, bootstrap=True 
[CV]  n_estimators=73, min_samples_split=10, min_samples_leaf=4, max_features=sqrt, max_depth=None, criterion=entropy, bootstrap=False, total=   6.2s
[CV] n_estimators=20, min_samples_split=5, min_samples_leaf=1, max_features=sqrt, max_depth=10, criterion=entropy, bootstrap=True 
[CV]  n_estimators=20, min_samples_split=5, min_samples_leaf=1, max_features=sqrt, max_depth=10, criterion=entropy, bootstrap=True, total=   0.8s
[CV] n_estimators

[CV] n_estimators=73, min_samples_split=10, min_samples_leaf=1, max_features=auto, max_depth=40, criterion=gini, bootstrap=False 
[CV]  n_estimators=500, min_samples_split=10, min_samples_leaf=4, max_features=auto, max_depth=60, criterion=entropy, bootstrap=False, total=  38.5s
[CV] n_estimators=446, min_samples_split=5, min_samples_leaf=1, max_features=sqrt, max_depth=None, criterion=gini, bootstrap=True 
[CV]  n_estimators=500, min_samples_split=10, min_samples_leaf=4, max_features=auto, max_depth=60, criterion=entropy, bootstrap=False, total=  39.9s
[CV] n_estimators=446, min_samples_split=5, min_samples_leaf=1, max_features=sqrt, max_depth=None, criterion=gini, bootstrap=True 
[CV]  n_estimators=126, min_samples_split=2, min_samples_leaf=2, max_features=sqrt, max_depth=10, criterion=entropy, bootstrap=False, total=   6.2s
[CV] n_estimators=446, min_samples_split=5, min_samples_leaf=1, max_features=sqrt, max_depth=None, criterion=gini, bootstrap=True 
[CV]  n_estimators=126, min_sam

[CV]  n_estimators=286, min_samples_split=2, min_samples_leaf=4, max_features=auto, max_depth=60, criterion=gini, bootstrap=True, total=   8.8s
[CV] n_estimators=340, min_samples_split=10, min_samples_leaf=2, max_features=sqrt, max_depth=50, criterion=gini, bootstrap=True 
[CV]  n_estimators=286, min_samples_split=10, min_samples_leaf=4, max_features=sqrt, max_depth=90, criterion=gini, bootstrap=True, total=   8.7s
[CV] n_estimators=340, min_samples_split=5, min_samples_leaf=2, max_features=auto, max_depth=20, criterion=gini, bootstrap=False 
[CV]  n_estimators=286, min_samples_split=10, min_samples_leaf=4, max_features=sqrt, max_depth=90, criterion=gini, bootstrap=True, total=   8.8s
[CV] n_estimators=340, min_samples_split=5, min_samples_leaf=2, max_features=auto, max_depth=20, criterion=gini, bootstrap=False 
[CV]  n_estimators=286, min_samples_split=2, min_samples_leaf=4, max_features=auto, max_depth=60, criterion=gini, bootstrap=True, total=   9.1s
[CV] n_estimators=340, min_sampl

[CV]  n_estimators=500, min_samples_split=10, min_samples_leaf=2, max_features=auto, max_depth=60, criterion=gini, bootstrap=False, total=  22.1s
[CV]  n_estimators=393, min_samples_split=2, min_samples_leaf=2, max_features=sqrt, max_depth=60, criterion=gini, bootstrap=True, total=  13.2s
[CV]  n_estimators=500, min_samples_split=10, min_samples_leaf=2, max_features=auto, max_depth=60, criterion=gini, bootstrap=False, total=  20.1s
[CV]  n_estimators=393, min_samples_split=2, min_samples_leaf=2, max_features=sqrt, max_depth=60, criterion=gini, bootstrap=True, total=   8.3s


[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed: 10.9min finished


RandomizedSearchCV(cv=3, error_score='raise',
          estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
          fit_params=None, iid=True, n_iter=100, n_jobs=-1,
          param_distributions={'n_estimators': [20, 73, 126, 180, 233, 286, 340, 393, 446, 500], 'max_features': ['auto', 'sqrt'], 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None], 'criterion': ['gini', 'entropy'], 'min_samples_split': [2, 5, 10], 'min_samples_leaf': [1, 2, 4], 'bootstrap': [True, False]},
          pre_dispatch='2*n_jobs', random_state=42, refit=True,
          return_train_score='warn', scoring=None, verbose=2)

In [52]:
rf_random.best_params_

{'n_estimators': 180,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 'auto',
 'max_depth': 80,
 'criterion': 'gini',
 'bootstrap': True}

In [82]:
def evaluate(model, test_features, test_labels):
    predictions = model.predict(test_features)
    errors = abs(predictions - test_labels)
    mape = 100 * np.mean(errors / test_labels)
    accuracy = 100 - mape
    print('Model Performance')
    print('Average Error: {:0.4f} degrees.'.format(np.mean(errors)))
    print('Accuracy = {:0.2f}%.'.format(accuracy))
    
    return accuracy


base_model = RandomForestRegressor(n_estimators =100,random_state = 42)
base_model.fit(X_train,y_train)
base_accuracy = evaluate(base_model,X_train,y_train)







Model Performance
Average Error: 0.5091 degrees.
Accuracy = nan%.


/home/siddanath/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.
/home/siddanath/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


In [83]:
best_random = rf_random.best_estimator_
random_accuracy = evaluate(best_random,X_train,y_train)

Model Performance
Average Error: 0.3879 degrees.
Accuracy = nan%.


/home/siddanath/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.
/home/siddanath/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.
